services:
  - type: web
    name: finparvai-backend   # change if you prefer another name
    env: docker
    plan: free
    region: oregon
    dockerfilePath: backend/Dockerfile
    buildCommand: ""
    startCommand: ""
    healthCheckPath: /health
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
    autoDeploy: true
