import os
import logging
from typing import Optional
try:
    from sendgrid import SendGridAPIClient
    from sendgrid.helpers.mail import Mail
    SENDGRID_AVAILABLE = True
except ImportError:
    SENDGRID_AVAILABLE = False

logger = logging.getLogger(__name__)

def send_cashflow_alert(to_email: str, business_name: str, gap: float, shortfall_summary: str) -> bool:
    """
    Sends an automated email alert via Twilio SendGrid if a cash flow shock is predicted.
    """
    api_key = os.getenv("SENDGRID_API_KEY")
    from_email = os.getenv("SENDGRID_FROM_EMAIL", "alerts@finparvai.demo")

    if not SENDGRID_AVAILABLE:
        logger.error("SendGrid is not installed. Run `pip install sendgrid`.")
        return False

    if not api_key:
        logger.warning("SENDGRID_API_KEY is not set. Skipping email alert.")
        return False

    subject = f"🚨 URGENT: Cashflow Shock Predicted for {business_name}"
    
    html_content = f"""
    <div style="font-family: Arial, sans-serif; padding: 20px; color: #333;">
        <h2 style="color: #d9534f;">⚠️ Cashflow Shock Alert</h2>
        <p>Hello {business_name},</p>
        <p>The FinParvai Decision Engine has detected a severe cash flow disruption in your upcoming projections.</p>
        <div style="background-color: #fcf8e3; border-left: 5px solid #f0ad4e; padding: 15px; margin: 20px 0;">
            <strong>Predicted Shortfall:</strong> ₹{gap:,.2f}<br/><br/>
            <strong>AI Analysis:</strong> {shortfall_summary}
        </div>
        <p>Please log in to your <a href="http://localhost:5173" style="color: #0275d8; text-decoration: none;">FinParvai Dashboard</a> immediately to view AI-generated recovery strategies (e.g., delaying flexible payables, pulling receivables early).</p>
        <br/>
        <p style="font-size: 12px; color: #777;">This is an automated decision-intelligence alert generated by FinParvai.</p>
    </div>
    """

    message = Mail(
        from_email=from_email,
        to_emails=to_email,
        subject=subject,
        html_content=html_content
    )

    try:
        sg = SendGridAPIClient(api_key)
        response = sg.send(message)
        logger.info(f"Alert email sent to {to_email}. Status code: {response.status_code}")
        return response.status_code in [200, 201, 202]
    except Exception as e:
        logger.error(f"Error sending email via SendGrid: {e}")
        return False
